# Generated by Django 4.2.21 on 2026-01-10 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Occupation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Профессия')),
                ('industry', models.CharField(max_length=200, verbose_name='Индустрия')),
                ('domain', models.CharField(max_length=200, verbose_name='Домен')),
            ],
            options={
                'verbose_name': 'Профессия',
                'verbose_name_plural': 'Профессии',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название страны')),
                ('continent', models.CharField(max_length=50, verbose_name='Континент')),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['continent'], name='pantheon_co_contine_5e5855_idx')],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название города')),
                ('state', models.CharField(blank=True, max_length=100, null=True, verbose_name='Штат')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Широта')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Долгота')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cities', to='pantheon.country', verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalFigure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_id', models.IntegerField(unique=True, verbose_name='ID статьи')),
                ('full_name', models.CharField(max_length=255, verbose_name='Полное имя')),
                ('birth_year', models.IntegerField(blank=True, null=True, verbose_name='Год рождения')),
                ('page_views', models.BigIntegerField(default=0, verbose_name='Количество просмотров страницы')),
                ('average_views', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Среднее количество просмотров')),
                ('historical_popularity_index', models.DecimalField(decimal_places=4, default=0.0, max_digits=10, verbose_name='Индекс исторической популярности')),
                ('article_languages', models.IntegerField(default=0, verbose_name='Количество языков статьи')),
                ('original_city_name', models.CharField(blank=True, max_length=100, verbose_name='Город (оригинал)')),
                ('original_country_name', models.CharField(blank=True, max_length=100, verbose_name='Страна (оригинал)')),
                ('original_continent_name', models.CharField(blank=True, max_length=100, verbose_name='Континент (оригинал)')),
                ('original_occupation_name', models.CharField(blank=True, max_length=200, verbose_name='Профессия (оригинал)')),
                ('original_industry_name', models.CharField(blank=True, max_length=200, verbose_name='Сфера деятельности (оригинал)')),
                ('original_domain_name', models.CharField(blank=True, max_length=200, verbose_name='Домен (оригинал)')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='historical_figures', to='pantheon.city', verbose_name='Место рождения')),
                ('occupation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='historical_figures', to='pantheon.occupation', verbose_name='Профессия')),
            ],
            options={
                'verbose_name': 'Историческая личность',
                'verbose_name_plural': 'Исторические личности',
                'ordering': ['full_name'],
                'indexes': [models.Index(fields=['birth_year'], name='pantheon_hi_birth_y_dfd42d_idx'), models.Index(fields=['historical_popularity_index'], name='pantheon_hi_histori_7b1985_idx'), models.Index(fields=['article_languages'], name='pantheon_hi_article_14f0b4_idx'), models.Index(fields=['page_views'], name='pantheon_hi_page_vi_578a71_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['name'], name='pantheon_ci_name_906678_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('name', 'country')},
        ),
    ]
